### PR TITLE
chore(gitignore): Ignore IntelliJ config folder

### PR DESCRIPTION
**Pull request by frassinier**

### CODE REVIEW

**Comment by jmfrancois** [comment]
From where the .gitignore files come from @talend-glorieux ?
I wonder if this is sth taken from the tools repository.
I would like to see this kind of stuff inside yo talend:dotfiles

**Comment by talend-glorieux** [comment]
@jmfrancois Agreed. .gitignore should be taken from the tools repo. What do you think about updating [the root one](https://github.com/Talend/tools/blob/master/.gitignore) and copy it with the generator?

**Comment by jmfrancois** [comment]
I would have said no because it's the gitingore of this repository and it has anything to do with what we should used. It can be error prone.
What do you think about adding it in that PR  ? https://github.com/Talend/tools/pull/16 which is about github-root dot files ?

**Comment by talend-glorieux** [comment]
@jmfrancois Yep, that would be the perfect place to add it. 
I'll just go ahead and merge that PR then make the appropriate changes to the PR https://github.com/Talend/tools/pull/16 and to the generator.

**Pull request merged**
